### ISSUE TITLE
"Error: No module named 'ipfx.nwb_reader'

### ISSUE THREAD

**Issue by jonathanTrinE** [AllenInstitute/biophys_optimize#13]
I'm running Windows10, python 3.7.7 and I'm getting this error when following the README and when doing the following:

In anaconda prompt,
pip install ipfx
pip install biophys_optimize 
python -m biophys_optimize.scripts.run_preprocessing --help
  File "C:\Users\USER\anaconda3\lib\site-packages\biophys_optimize-0.1.0-py3.7.egg\biophys_optimize\scripts\run_preprocessing.py", line 7, in <module>
    from ipfx.nwb_reader import create_nwb_reader
ModuleNotFoundError: No module named 'ipfx.nwb_reader'

I'm trying to use biophys_optimize for an ABI-Cell Type (Cell ID: 477127614).

**Comment by gouwens** [comment]
The release of IPFX 1.0 made several breaking changes from the prior versions (including to how to access NWB files, and dropping support for NWB1 files), so I need to update biophys_optimize in response to those changes, or restrict it to an earlier version (if that is accessible to external users). I'm trying to determine the best course of action at the moment.

**Comment by gouwens** [comment]
I am going to keep the default version of biophys_optimize working with NWB1 files (which are what are available still from the Allen Cell Types Database, including the cell that you mention). Therefore, you will need to install an older version of IPFX available from GitHub; I have added instructions for how to do that to the README.

In addition, in a new branch, I'll update biophys_optimize to work with NWB2 files and IPFX v1.0. Eventually, I will switch the default to that one when data from all the cells are available in the NWB2 format.

**Comment by jonathanTrinE** [comment]
I appreciate your response!

**Comment by jonathanTrinE** [comment]
I apologize for prematurely closing the issue:
I uninstalled ipfx and biophys_optimize and followed the new instructions.  However, I receive an error when I run the following commands for IPFX:
$ git clone --branch=nwb1-support https://github.com/AllenInstitute/ipfx.git
$ cd ipfx
$ pip install -e .
Here is the error:
$ python setup.py egg_info
error in ipfx setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers; Parse error at "'+https:/'": Expected stringEnd

**Comment by jonathanTrinE** [comment]
Hi 
I found that in the requirements.txt file, line 12, add 'pip @'
pip @ git+https://github.com/neurodatawithoutborders/pynwb@dev
 I was able to run 
pip install -e . with no errors after that.  

Hope this helps!
